name: Build PHP binaries

on:
    push:
      branches: "**"
      tags-ignore: "php-**"
    pull_request:
    workflow_dispatch:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - name: Clone musl-cross-make repository
        run: git clone https://github.com/TukangM/musl-cross-make

      - name: Install tools and dependencies for musl-cross-make and install musl-cross-make binary
        run: |
          cd musl-cross-make
          sudo apt-get update
          sudo apt-get install make autoconf automake libtool m4 wget gzip bzip2 bison g++ git cmake pkg-config re2c
          sudo apt-get install libtool-bin
          sudo make install -j${{ steps.cpu-cores.outputs.count }}
          cd ..
          

      - name: wget compile.sh and compile and tar.gz or achive the binary
        run: |
          pwd
          wget https://raw.githubusercontent.com/dvtruong1001/php8-aarch64-builds/main/compile.sh -O compile.sh
          bash compile.sh -t android-aarch64 -x -j${{ steps.cpu-cores.outputs.count }} -P5 -D
          pwd
          tar -czf ./PHP-Linux-aarch64-PM5.tar.gz bin
          tar -czf ./PHP-Linux-aarch64-PM5-debugging-symbols.tar.gz bin-debug


      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Linux-aarch64-PM5
          path: |
            ./PHP-Linux-aarch64-PM5*.tar.gz
            install.log
            compile.sh
          if-no-files-found: error
